### ISSUE TITLE
getJson and getCsv are now merged into hugo-master branch

### ISSUE THREAD

**Issue by SchumacherFM** [pcdummy/hugo-lightslider-example#1]
hey,

please update your repo and point to hugos master branch as my feature has been merged!

[https://github.com/spf13/hugo/pull/748#issuecomment-74804028](https://github.com/spf13/hugo/pull/748#issuecomment-74804028)

I've also mentioned your module in the docs of hugo: https://github.com/spf13/hugo/blob/master/docs%2Fcontent%2Fextras%2Fdynamiccontent.md#examples

Thanks!

**Comment by SchumacherFM** [comment]
I've mentioned your module in the docs of hugo: https://github.com/spf13/hugo/blob/master/docs%2Fcontent%2Fextras%2Fdynamiccontent.md#examples

**Comment by SchumacherFM** [comment]
What's the status?

**Comment by jochumdev** [comment]
Fixed the readme, had a lot to do. Thanks for reporting and your work on Hugo itself.

**Comment by SchumacherFM** [comment]
Thanks! :-)
