### ISSUE TITLE
generated site is down

### ISSUE THREAD

**Issue by laniehei** [pcdummy/hugo-lightslider-example#4]
<img width="896" alt="Screen Shot 2019-09-28 at 3 34 54 PM" src="https://user-images.githubusercontent.com/13442634/65822213-92602880-e205-11e9-8a37-1e17064354a9.png">

**Comment by Phantasm23** [comment]
I can also confirm this.

**Comment by jochumdev** [comment]
I'm now hosting hugo-lightslider-example on GitHub Pages https://pcdummy.github.io/hugo-lightslider-example/
